# Generated by Django 2.2.4 on 2019-09-29 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_agregar',
            fields=[
                ('cod_ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('latitud', models.CharField(max_length=200)),
                ('longitud', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('colegio', 'Colegio'), ('iglesia', 'Iglesia'), ('plaza', 'Plaza'), ('restaurante', 'Restaurante'), ('alojamiento', 'Alojamiento')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='colegio',
            fields=[
                ('cod_colegio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_fundacion', models.CharField(max_length=200)),
                ('clasificacion', models.CharField(max_length=200)),
                ('cod_ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_lugar.admin_agregar')),
            ],
        ),
    ]
