# Generated by Django 2.2.4 on 2019-10-09 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_lugar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurante',
            old_name='cod_restaurant',
            new_name='cod_restaurante',
        ),
    ]
