# Generated by Django 2.2.4 on 2019-10-14 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud_lugar', '0002_auto_20191009_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='evento',
            fields=[
                ('cod_evento', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_evento', models.CharField(max_length=300)),
                ('fecha', models.DateField()),
                ('hora_ini', models.DateTimeField(null=True)),
                ('hora_fin', models.DateTimeField(null=True)),
                ('descripcion', models.TextField(max_length=800, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='foto',
            fields=[
                ('cod_foto', models.AutoField(primary_key=True, serialize=False)),
                ('ruta', models.FileField(null=True, upload_to='')),
                ('cod_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_lugar.evento')),
            ],
        ),
    ]
