# Generated by Django 2.2.4 on 2019-10-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_lugar', '0003_evento_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='hora_fin',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='hora_ini',
            field=models.TimeField(),
        ),
    ]
