# Generated by Django 2.2.4 on 2019-10-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_lugar', '0004_auto_20191015_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='hora_fin',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='hora_ini',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='foto',
            name='ruta',
            field=models.FileField(null=True, upload_to='myfolder/'),
        ),
    ]
