# Generated by Django 2.2.4 on 2019-10-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_lugar', '0005_auto_20191015_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alojamiento',
            name='fecha_fundacion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='fecha_fundacion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='iglesia',
            name='fecha_fundacion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='plaza',
            name='fecha_fundacion',
            field=models.DateField(),
        ),
    ]
